### ISSUE TITLE
Command line parameters 

### ISSUE THREAD

**Issue by nhershy** [nhershy/CorruptVideoFileInspector#10]
Eg. to pass on folder path, start the job or just open the window and wait.

**Comment by chapmanjacobd** [comment]
I made a 5 minute attempt to add this functionality to my existing media scanner: https://github.com/chapmanjacobd/library/commit/572c61bcc9efca13ba3e0fb8e4afd2bedaf97984#diff-237f28ad7b701e6f58f4627e8970308bd3015c9ac69bdca4d0341813a8166b0e

I have not tested this specific functionality but you should be able to do:

https://github.com/chapmanjacobd/library/blob/main/Windows.md

```
pip install xklb
lb fsadd --check-corrupt test.db .\videos\ >> corrupt_videos.txt
```

If it launches too many concurrent ffmpeg decoding threads, you can limit it with a flag like `--io-multiplier 0.5` or `0.2`
