### ISSUE TITLE
Windows GUI app doesn't scan anything - "Currently Processing: N/A"

### ISSUE THREAD

**Issue by nCuky** [nhershy/CorruptVideoFileInspector#2]
Hello.
I stumbled upon [your comment](https://superuser.com/questions/100288/how-can-i-check-the-integrity-of-a-video-file-avi-mpeg-mp4#comment2764236_100288) and found your app, which looks very promising. However, when I tried to execute a scan on a folder with .MOV files, it didn't do anything. It says "Currenty Processing: N/A" and that's it, nothing else happens:

![image](https://user-images.githubusercontent.com/25561013/226095735-b0a59035-e718-4649-8c1f-dd669448cf4f.png)

This happened on multiple folders I tried, some with .MOV files and some with .MP4 files.
What could be the problem? Does the app come with a built-in ffmpeg library or should I download it manually? Does it support .MOV and .MP4 files out of the box or should I configure something somewhere?

I'm using Windows 10 with the GUI wrapper of the app.

Thank you very much!

**Comment by nCuky** [comment]
Upon further investigation I discovered that in methods `countAllVideoFiles()` and `inspectVideoFiles()`, the conditions to check the file compare the filename (**as-is**) with the allowed exceptions (which are all in lowercase), and thus uppercase extensions aren't matched (my file ends with '.MP4' and not '.mp4').
I fixed the condition `if file.endswith(tuple(VIDEO_EXTENSIONS)):` to `if file.lower().endswith(tuple(VIDEO_EXTENSIONS)):`.

Then I got another problem in `inspectVideoFiles()`. The statement `output, error = proc.communicate()` returned an error. Here are the returned values:
`error = b''`
`output = b"'.' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"`

This is beyond my capabilities, so I would be very glad if you could understand what causes this and fix it.

Thanks!

**Comment by nhershy** [comment]
This issue has now been fixed. Please download the newest version for Windows
